# Generated by Django 5.1.3 on 2024-11-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twix', '0007_alter_profile_profile_image_alter_profile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/newmainicon.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='twix',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='twix_photos/'),
        ),
        migrations.AlterField(
            model_name='twix',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
