# Generated by Django 5.1.3 on 2024-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twix', '0011_rename_homepage_link_profile_email_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/icon.png', null=True, upload_to='images/'),
        ),
    ]
